name: Org membership request form
description: request we add you to this github organization
title: "Github Org Membership Request for: "

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this membership request !
        We need a couple pieces of information to enable you to participate.

  - type: input
    id: github_username
    attributes:
      label: Github Username
      placeholder: myusername
    validations:
      required: false

  - type: input
    id: github_url
    attributes:
      label: Github URL
      placeholder: "https://github.com/myusername"
    validations:
      required: false

