---
name: Github Org Access Request
description: request adding you to this github org
title: "Github Org Access Request for: "
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        We need some minimal information to add you as an authorized member of this github organization.  We do this to try to avoid being spammed by users and content not related to WeeWX.  Thank you.

  - type: input
    id: username
    attributes:
      label: Username
      description: What is your github username
      placeholder: my_username_here
    validations:
      required: false

  - type: input
    id: url
    attributes:
      label: Github URL
      description: What is your github account URL
      placeholder: https://github.com/my_username_here
    validations:
      required: false

