name: Membership Request Form
description: request we add you to this github organization
title: "Membership Request for: "
labels: []
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this form.
        We need a few pieces of information to add you to this github organization.

  - type: input
    id: version
    attributes:
      label: Username
      description: Your github username
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Github URL
      description: Your github url
    validations:
      required: false


